In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

In [152]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score

In [153]:
df = pd.read_csv("TATAMOTORS_NSE_1995-2025.csv")

In [154]:
df.head()

Unnamed: 0        Date      Symbol   Open   High    Low  Close  PrevClose  \
0         223  1995-01-02  TATAMOTORS  517.5  524.7  517.5  524.2      522.0   
1         224  1995-01-03  TATAMOTORS  518.0  520.0  515.0  515.0      524.2   
2         225  1995-01-04  TATAMOTORS  515.0  515.0  515.0  515.0      515.0   
3         226  1995-01-05  TATAMOTORS  480.0  480.0  480.0  480.0      515.0   
4         227  1995-01-06  TATAMOTORS  495.0  501.0  495.0  498.7      480.0   

   Volume  Turnover    VWAP  Trades  Daily_Return_%  MA_20  MA_50  
0    1100  573530.0  521.39     NaN        0.421456    NaN    NaN  
1    1500  775450.0  516.97     NaN       -1.755055    NaN    NaN  
2     300  154500.0  515.00     NaN        0.000000    NaN    NaN  
3      50   24000.0  480.00     NaN       -6.796117    NaN    NaN  
4     200   99550.0  497.75     NaN        3.895833    NaN    NaN

In [155]:
df['Prediction'] = df['Close'].shift(-1)

In [156]:
df

Unnamed: 0        Date      Symbol    Open    High     Low   Close  \
0            223  1995-01-02  TATAMOTORS  517.50  524.70  517.50  524.20   
1            224  1995-01-03  TATAMOTORS  518.00  520.00  515.00  515.00   
2            225  1995-01-04  TATAMOTORS  515.00  515.00  515.00  515.00   
3            226  1995-01-05  TATAMOTORS  480.00  480.00  480.00  480.00   
4            227  1995-01-06  TATAMOTORS  495.00  501.00  495.00  498.70   
...          ...         ...         ...     ...     ...     ...     ...   
7799        7660  2025-08-12  TATAMOTORS  651.10  660.95  650.80  654.10   
7800        7661  2025-08-13  TATAMOTORS  657.20  667.00  656.65  663.75   
7801        7662  2025-08-14  TATAMOTORS  666.00  666.55  657.70  664.60   
7802        7663  2025-08-18  TATAMOTORS  677.00  685.00  672.90  676.00   
7803        7664  2025-08-19  TATAMOTORS  676.75  703.35  673.10  700.25   

      PrevClose    Volume      Turnover    VWAP    Trades  Daily_Return_%  \
0        522.00      1100  5.735300e+05  521.39       NaN        0.421456   
1        524.20      1500  7.754500e+05  516.97       NaN       -1.755055   
2        515.00       300  1.545000e+05  515.00       NaN        0.000000   
3        515.00        50  2.400000e+04  480.00       NaN       -6.796117   
4        480.00       200  9.955000e+04  497.75       NaN        3.895833   
...         ...       ...           ...     ...       ...             ...   
7799     653.75  11212223  7.348231e+09  655.38  223425.0        0.053537   
7800     654.10   7557556  5.016113e+09  663.72  133862.0        1.475310   
7801     663.75   6250494  4.140530e+09  662.43  115002.0        0.128060   
7802     664.60  14226172  9.655303e+09  678.70  165366.0        1.715317   
7803     676.00  19440384  1.351303e+10  695.10  282726.0        3.587278   

         MA_20    MA_50  Prediction  
0          NaN      NaN      515.00  
1          NaN      NaN      515.00  
2          NaN      NaN      480.00  
3          NaN      NaN      498.70  
4          NaN      NaN      495.00  
...        ...      ...         ...  
7799  669.3700  683.496      663.75  
7800  668.6075  682.568      664.60  
7801  667.7525  681.640      676.00  
7802  667.5400  680.804      700.25  
7803  668.1800  680.164         NaN  

[7804 rows x 16 columns]

In [157]:
X = np.array(df[['Close']])
y = np.array(df['Prediction'])

In [158]:
X

array([[524.2 ],
       [515.  ],
       [515.  ],
       ...,
       [664.6 ],
       [676.  ],
       [700.25]])

In [159]:
y

array([515.  , 515.  , 480.  , ..., 676.  , 700.25,    nan])

In [160]:
X = X[:-1]
y = y[:-1]

In [161]:
X

array([[524.2 ],
       [515.  ],
       [515.  ],
       ...,
       [663.75],
       [664.6 ],
       [676.  ]])

In [162]:
y

array([515.  , 515.  , 480.  , ..., 664.6 , 676.  , 700.25])

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [164]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('regressor', LinearRegression())
])

In [165]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('regressor', LinearRegression())])

In [166]:
predictions = pipeline.predict(X_test)

In [167]:
joblib.dump(pipeline, 'pipeline.pkl')
joblib.dump(model, 'model.pkl')


['model.pkl']

In [168]:
print(f"Mean Squared Error: {mse}")
print(f"R² Score: {r2}")

Mean Squared Error: 123.53016903476596
R² Score: 0.9981840345330408


In [169]:
output_df = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': predictions
})

In [170]:
output_df.to_csv('output.csv', index=False)

print("✅ Saved 'pipeline.pkl', 'model.pkl', and 'output.csv'")


✅ Saved 'pipeline.pkl', 'model.pkl', and 'output.csv'
